server.port=8080

# Route 1: Auth Service (Login, Register, Users)
spring.cloud.gateway.routes[0].id=autherservice
spring.cloud.gateway.routes[0].uri=http://autherservice:8090
spring.cloud.gateway.routes[0].predicates[0]=Path=/login, /register, /getuser, /home

# Route 2: Order Service
spring.cloud.gateway.routes[1].id=orderservice
spring.cloud.gateway.routes[1].uri=http://orderservice:8091
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**
